project_id = "bpflebtklgnivcanhlbp"

[functions.analyze-symptoms]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.ocr-prescription]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.broadcast-delivery-request]
verify_jwt = false

[functions.cart-order-broadcast]
verify_jwt = false

[functions.cart-order-response]
verify_jwt = false

[functions.cart-broadcast-escalation]
verify_jwt = false
