
project_id = "bpflebtklgnivcanhlbp"

[functions.analyze-symptoms]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.ocr-prescription]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.retry-delivery-broadcast]
verify_jwt = false
